version: "3.8"

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0
    ports:
      - "8545:8545"
    networks:
      - drpc-network

  # Contract deployment service
  deploy:
    image: ghcr.io/foundry-rs/foundry:latest
    depends_on:
      - anvil
    working_dir: /app
    volumes:
      - ./contracts:/app
      - ./contracts/.env:/app/.env
    command: >
      bash -c "
        echo 'Waiting for anvil to start...' &&
        sleep 5 &&
        forge script script/Deploy.s.sol --rpc-url http://anvil:8545 --broadcast
      "
    environment:
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    networks:
      - drpc-network

  # RPC Node Service
  node:
    build:
      context: ./node
    ports:
      - "8080:8080"
    depends_on:
      - deploy
    environment:
      - RPC_URL=http://anvil:8545
      - FORGE_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - PORT=8080
    env_file:
      - ./contracts/.env
    networks:
      - drpc-network

  # Frontend Service
  ui:
    build:
      context: ./ui
    ports:
      - "5173:5173"
    depends_on:
      - node
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - drpc-network

networks:
  drpc-network:
    driver: bridge
